// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/adcom.proto

package com.iabtechlab.adcom.types;

public final class Adcom {
  private Adcom() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.iabtechlab.adcom.types.CategoryTaxonomy}
   */
  public enum CategoryTaxonomy
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_CATEGORY_TAXONOMY = 0;</code>
     */
    UNKNOWN_CATEGORY_TAXONOMY(0),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN_CATEGORY_TAXONOMY = 0;</code>
     */
    public static final int UNKNOWN_CATEGORY_TAXONOMY_VALUE = 0;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CategoryTaxonomy valueOf(int value) {
      return forNumber(value);
    }

    public static CategoryTaxonomy forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_CATEGORY_TAXONOMY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CategoryTaxonomy>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CategoryTaxonomy> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CategoryTaxonomy>() {
            public CategoryTaxonomy findValueByNumber(int number) {
              return CategoryTaxonomy.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.iabtechlab.adcom.types.Adcom.getDescriptor().getEnumTypes().get(0);
    }

    private static final CategoryTaxonomy[] VALUES = values();

    public static CategoryTaxonomy valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CategoryTaxonomy(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.iabtechlab.adcom.types.CategoryTaxonomy)
  }

  public interface AdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.iabtechlab.adcom.types.Ad)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>repeated string adomain = 2;</code>
     */
    java.util.List<java.lang.String>
        getAdomainList();
    /**
     * <code>repeated string adomain = 2;</code>
     */
    int getAdomainCount();
    /**
     * <code>repeated string adomain = 2;</code>
     */
    java.lang.String getAdomain(int index);
    /**
     * <code>repeated string adomain = 2;</code>
     */
    com.google.protobuf.ByteString
        getAdomainBytes(int index);

    /**
     * <code>.com.iabtechlab.adcom.types.CategoryTaxonomy cattax = 3;</code>
     */
    int getCattaxValue();
    /**
     * <code>.com.iabtechlab.adcom.types.CategoryTaxonomy cattax = 3;</code>
     */
    com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy getCattax();

    /**
     * <code>.google.protobuf.Any ext = 500;</code>
     */
    boolean hasExt();
    /**
     * <code>.google.protobuf.Any ext = 500;</code>
     */
    com.google.protobuf.Any getExt();
    /**
     * <code>.google.protobuf.Any ext = 500;</code>
     */
    com.google.protobuf.AnyOrBuilder getExtOrBuilder();
  }
  /**
   * Protobuf type {@code com.iabtechlab.adcom.types.Ad}
   */
  public  static final class Ad extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.iabtechlab.adcom.types.Ad)
      AdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Ad.newBuilder() to construct.
    private Ad(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Ad() {
      id_ = "";
      adomain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      cattax_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Ad(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                adomain_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              adomain_.add(s);
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              cattax_ = rawValue;
              break;
            }
            case 4002: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (ext_ != null) {
                subBuilder = ext_.toBuilder();
              }
              ext_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ext_);
                ext_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          adomain_ = adomain_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.iabtechlab.adcom.types.Adcom.internal_static_com_iabtechlab_adcom_types_Ad_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.iabtechlab.adcom.types.Adcom.internal_static_com_iabtechlab_adcom_types_Ad_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.iabtechlab.adcom.types.Adcom.Ad.class, com.iabtechlab.adcom.types.Adcom.Ad.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADOMAIN_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList adomain_;
    /**
     * <code>repeated string adomain = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAdomainList() {
      return adomain_;
    }
    /**
     * <code>repeated string adomain = 2;</code>
     */
    public int getAdomainCount() {
      return adomain_.size();
    }
    /**
     * <code>repeated string adomain = 2;</code>
     */
    public java.lang.String getAdomain(int index) {
      return adomain_.get(index);
    }
    /**
     * <code>repeated string adomain = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAdomainBytes(int index) {
      return adomain_.getByteString(index);
    }

    public static final int CATTAX_FIELD_NUMBER = 3;
    private int cattax_;
    /**
     * <code>.com.iabtechlab.adcom.types.CategoryTaxonomy cattax = 3;</code>
     */
    public int getCattaxValue() {
      return cattax_;
    }
    /**
     * <code>.com.iabtechlab.adcom.types.CategoryTaxonomy cattax = 3;</code>
     */
    public com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy getCattax() {
      @SuppressWarnings("deprecation")
      com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy result = com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy.valueOf(cattax_);
      return result == null ? com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy.UNRECOGNIZED : result;
    }

    public static final int EXT_FIELD_NUMBER = 500;
    private com.google.protobuf.Any ext_;
    /**
     * <code>.google.protobuf.Any ext = 500;</code>
     */
    public boolean hasExt() {
      return ext_ != null;
    }
    /**
     * <code>.google.protobuf.Any ext = 500;</code>
     */
    public com.google.protobuf.Any getExt() {
      return ext_ == null ? com.google.protobuf.Any.getDefaultInstance() : ext_;
    }
    /**
     * <code>.google.protobuf.Any ext = 500;</code>
     */
    public com.google.protobuf.AnyOrBuilder getExtOrBuilder() {
      return getExt();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      for (int i = 0; i < adomain_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, adomain_.getRaw(i));
      }
      if (cattax_ != com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy.UNKNOWN_CATEGORY_TAXONOMY.getNumber()) {
        output.writeEnum(3, cattax_);
      }
      if (ext_ != null) {
        output.writeMessage(500, getExt());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < adomain_.size(); i++) {
          dataSize += computeStringSizeNoTag(adomain_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAdomainList().size();
      }
      if (cattax_ != com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy.UNKNOWN_CATEGORY_TAXONOMY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, cattax_);
      }
      if (ext_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(500, getExt());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.iabtechlab.adcom.types.Adcom.Ad)) {
        return super.equals(obj);
      }
      com.iabtechlab.adcom.types.Adcom.Ad other = (com.iabtechlab.adcom.types.Adcom.Ad) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getAdomainList()
          .equals(other.getAdomainList());
      result = result && cattax_ == other.cattax_;
      result = result && (hasExt() == other.hasExt());
      if (hasExt()) {
        result = result && getExt()
            .equals(other.getExt());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (getAdomainCount() > 0) {
        hash = (37 * hash) + ADOMAIN_FIELD_NUMBER;
        hash = (53 * hash) + getAdomainList().hashCode();
      }
      hash = (37 * hash) + CATTAX_FIELD_NUMBER;
      hash = (53 * hash) + cattax_;
      if (hasExt()) {
        hash = (37 * hash) + EXT_FIELD_NUMBER;
        hash = (53 * hash) + getExt().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.iabtechlab.adcom.types.Adcom.Ad parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.iabtechlab.adcom.types.Adcom.Ad parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.iabtechlab.adcom.types.Adcom.Ad prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.iabtechlab.adcom.types.Ad}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.iabtechlab.adcom.types.Ad)
        com.iabtechlab.adcom.types.Adcom.AdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.iabtechlab.adcom.types.Adcom.internal_static_com_iabtechlab_adcom_types_Ad_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.iabtechlab.adcom.types.Adcom.internal_static_com_iabtechlab_adcom_types_Ad_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.iabtechlab.adcom.types.Adcom.Ad.class, com.iabtechlab.adcom.types.Adcom.Ad.Builder.class);
      }

      // Construct using com.iabtechlab.adcom.types.Adcom.Ad.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        adomain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        cattax_ = 0;

        if (extBuilder_ == null) {
          ext_ = null;
        } else {
          ext_ = null;
          extBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.iabtechlab.adcom.types.Adcom.internal_static_com_iabtechlab_adcom_types_Ad_descriptor;
      }

      @java.lang.Override
      public com.iabtechlab.adcom.types.Adcom.Ad getDefaultInstanceForType() {
        return com.iabtechlab.adcom.types.Adcom.Ad.getDefaultInstance();
      }

      @java.lang.Override
      public com.iabtechlab.adcom.types.Adcom.Ad build() {
        com.iabtechlab.adcom.types.Adcom.Ad result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.iabtechlab.adcom.types.Adcom.Ad buildPartial() {
        com.iabtechlab.adcom.types.Adcom.Ad result = new com.iabtechlab.adcom.types.Adcom.Ad(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          adomain_ = adomain_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.adomain_ = adomain_;
        result.cattax_ = cattax_;
        if (extBuilder_ == null) {
          result.ext_ = ext_;
        } else {
          result.ext_ = extBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.iabtechlab.adcom.types.Adcom.Ad) {
          return mergeFrom((com.iabtechlab.adcom.types.Adcom.Ad)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.iabtechlab.adcom.types.Adcom.Ad other) {
        if (other == com.iabtechlab.adcom.types.Adcom.Ad.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.adomain_.isEmpty()) {
          if (adomain_.isEmpty()) {
            adomain_ = other.adomain_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAdomainIsMutable();
            adomain_.addAll(other.adomain_);
          }
          onChanged();
        }
        if (other.cattax_ != 0) {
          setCattaxValue(other.getCattaxValue());
        }
        if (other.hasExt()) {
          mergeExt(other.getExt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.iabtechlab.adcom.types.Adcom.Ad parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.iabtechlab.adcom.types.Adcom.Ad) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList adomain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAdomainIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          adomain_ = new com.google.protobuf.LazyStringArrayList(adomain_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string adomain = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAdomainList() {
        return adomain_.getUnmodifiableView();
      }
      /**
       * <code>repeated string adomain = 2;</code>
       */
      public int getAdomainCount() {
        return adomain_.size();
      }
      /**
       * <code>repeated string adomain = 2;</code>
       */
      public java.lang.String getAdomain(int index) {
        return adomain_.get(index);
      }
      /**
       * <code>repeated string adomain = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAdomainBytes(int index) {
        return adomain_.getByteString(index);
      }
      /**
       * <code>repeated string adomain = 2;</code>
       */
      public Builder setAdomain(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAdomainIsMutable();
        adomain_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adomain = 2;</code>
       */
      public Builder addAdomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAdomainIsMutable();
        adomain_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adomain = 2;</code>
       */
      public Builder addAllAdomain(
          java.lang.Iterable<java.lang.String> values) {
        ensureAdomainIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, adomain_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adomain = 2;</code>
       */
      public Builder clearAdomain() {
        adomain_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string adomain = 2;</code>
       */
      public Builder addAdomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAdomainIsMutable();
        adomain_.add(value);
        onChanged();
        return this;
      }

      private int cattax_ = 0;
      /**
       * <code>.com.iabtechlab.adcom.types.CategoryTaxonomy cattax = 3;</code>
       */
      public int getCattaxValue() {
        return cattax_;
      }
      /**
       * <code>.com.iabtechlab.adcom.types.CategoryTaxonomy cattax = 3;</code>
       */
      public Builder setCattaxValue(int value) {
        cattax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.iabtechlab.adcom.types.CategoryTaxonomy cattax = 3;</code>
       */
      public com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy getCattax() {
        @SuppressWarnings("deprecation")
        com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy result = com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy.valueOf(cattax_);
        return result == null ? com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.iabtechlab.adcom.types.CategoryTaxonomy cattax = 3;</code>
       */
      public Builder setCattax(com.iabtechlab.adcom.types.Adcom.CategoryTaxonomy value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        cattax_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.iabtechlab.adcom.types.CategoryTaxonomy cattax = 3;</code>
       */
      public Builder clearCattax() {
        
        cattax_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any ext_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> extBuilder_;
      /**
       * <code>.google.protobuf.Any ext = 500;</code>
       */
      public boolean hasExt() {
        return extBuilder_ != null || ext_ != null;
      }
      /**
       * <code>.google.protobuf.Any ext = 500;</code>
       */
      public com.google.protobuf.Any getExt() {
        if (extBuilder_ == null) {
          return ext_ == null ? com.google.protobuf.Any.getDefaultInstance() : ext_;
        } else {
          return extBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any ext = 500;</code>
       */
      public Builder setExt(com.google.protobuf.Any value) {
        if (extBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ext_ = value;
          onChanged();
        } else {
          extBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any ext = 500;</code>
       */
      public Builder setExt(
          com.google.protobuf.Any.Builder builderForValue) {
        if (extBuilder_ == null) {
          ext_ = builderForValue.build();
          onChanged();
        } else {
          extBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any ext = 500;</code>
       */
      public Builder mergeExt(com.google.protobuf.Any value) {
        if (extBuilder_ == null) {
          if (ext_ != null) {
            ext_ =
              com.google.protobuf.Any.newBuilder(ext_).mergeFrom(value).buildPartial();
          } else {
            ext_ = value;
          }
          onChanged();
        } else {
          extBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any ext = 500;</code>
       */
      public Builder clearExt() {
        if (extBuilder_ == null) {
          ext_ = null;
          onChanged();
        } else {
          ext_ = null;
          extBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any ext = 500;</code>
       */
      public com.google.protobuf.Any.Builder getExtBuilder() {
        
        onChanged();
        return getExtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any ext = 500;</code>
       */
      public com.google.protobuf.AnyOrBuilder getExtOrBuilder() {
        if (extBuilder_ != null) {
          return extBuilder_.getMessageOrBuilder();
        } else {
          return ext_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : ext_;
        }
      }
      /**
       * <code>.google.protobuf.Any ext = 500;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getExtFieldBuilder() {
        if (extBuilder_ == null) {
          extBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getExt(),
                  getParentForChildren(),
                  isClean());
          ext_ = null;
        }
        return extBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.iabtechlab.adcom.types.Ad)
    }

    // @@protoc_insertion_point(class_scope:com.iabtechlab.adcom.types.Ad)
    private static final com.iabtechlab.adcom.types.Adcom.Ad DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.iabtechlab.adcom.types.Adcom.Ad();
    }

    public static com.iabtechlab.adcom.types.Adcom.Ad getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Ad>
        PARSER = new com.google.protobuf.AbstractParser<Ad>() {
      @java.lang.Override
      public Ad parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ad(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Ad> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Ad> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.iabtechlab.adcom.types.Adcom.Ad getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_iabtechlab_adcom_types_Ad_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_iabtechlab_adcom_types_Ad_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036src/main/resources/adcom.proto\022\032com.ia" +
      "btechlab.adcom.types\032\031google/protobuf/an" +
      "y.proto\"\203\001\n\002Ad\022\n\n\002id\030\001 \001(\t\022\017\n\007adomain\030\002 " +
      "\003(\t\022<\n\006cattax\030\003 \001(\0162,.com.iabtechlab.adc" +
      "om.types.CategoryTaxonomy\022\"\n\003ext\030\364\003 \001(\0132" +
      "\024.google.protobuf.Any*1\n\020CategoryTaxonom" +
      "y\022\035\n\031UNKNOWN_CATEGORY_TAXONOMY\020\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_com_iabtechlab_adcom_types_Ad_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_iabtechlab_adcom_types_Ad_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_iabtechlab_adcom_types_Ad_descriptor,
        new java.lang.String[] { "Id", "Adomain", "Cattax", "Ext", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
